spring:
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    schema: classpath:db.sql
    generate-unique-name: false
    initialization-mode: always