version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps: 
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify -Dmaven.test.skip=true
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
  mydeploy:
    docker:
      - image: docker:19.03.12
    steps:
      - setup_remote_docker:
          version: 19.03.12
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Grant execute permissions to build.sh
          command: chmod +x build.sh
      - run:
          name: Execute build script
          command: ./build.sh
workflows:
  build-and-test:
    jobs:
      - test-java
      - mydeploy:
          requires:
            - test-java